version: '3.9'
services:
  kafka1:
    image: apache/kafka:4.1.0
    container_name: kafka1

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      CLUSTER_ID: 'NhzDqHe8TgW6iJmwh2SFGg'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://kafka1:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_UNSTABLE_API_VERSION_ENABLE: "true"
      KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer,share
      KAFKA_SHARE_GROUP_PROTOCOL_ENABLE: "true"

    networks:
      - kafka-net
      
    volumes:
      - ./kafka1-storage:/tmp/kafka-logs

  kafka2:
    image: apache/kafka:4.1.0
    container_name: kafka2

    ports:
      - "9094:9092"

    environment:
      CLUSTER_ID: 'NhzDqHe8TgW6iJmwh2SFGg'
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://kafka2:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:29092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_UNSTABLE_API_VERSION_ENABLE: "true"
      KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer,share
      KAFKA_SHARE_GROUP_PROTOCOL_ENABLE: "true"

    networks:
      - kafka-net
      
    volumes:
      - ./kafka2-storage:/tmp/kafka-logs

    depends_on:
      - kafka1

  kafka3:
    image: apache/kafka:4.1.0
    container_name: kafka3

    ports:
      - "9095:9092"

    environment:
      CLUSTER_ID: 'NhzDqHe8TgW6iJmwh2SFGg'
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://kafka3:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:29092,EXTERNAL://localhost:9095
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_UNSTABLE_API_VERSION_ENABLE: "true"
      KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer,share
      KAFKA_SHARE_GROUP_PROTOCOL_ENABLE: "true"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - kafka-net  
    volumes:
      - ./kafka3-storage:/tmp/kafka-logs
    
    depends_on:
      - kafka1
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: pro-kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

    networks:
      - kafka-net

    environment:
      KAFKA_CLUSTERS_0_NAME: "multi-node-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: true
      
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "7070:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  
    networks:
      - kafka-net

    environment:
      KAFKA_BROKERS: "kafka1:29092,kafka2:29092,kafka3:29092"
      SCHEMAREGISTRY_ENABLED: true
      SCHEMAREGISTRY_URLS: http://schema-registry:8081

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  
    networks:
      - kafka-net

    volumes:
      - ./kafka-storage:/tmp-kafka-logs

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:29092, kafka2:29092, kafka3:29092

networks:
  kafka-net:
    name: kafka-net

volumes:
  kafka-logs:
    driver: local
