version: '3.9'
services:
  kafka1:
    image: apache/kafka:latest
    container_name: kafka1

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      CLUSTER_ID: 'Eq2RE98JRhiAGPiQ0AJH6Q'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: BROKER://kafka1:29092,CLIENT://localhost:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:29092,CLIENT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093

    networks:
      - kafka-net
      
    volumes:
      - ./kafka1-storage:/tmp/kafka-logs

  kafka2:
    image: apache/kafka:latest
    container_name: kafka2

    ports:
      - "9094:9094"

    environment:
      CLUSTER_ID: 'Eq2RE98JRhiAGPiQ0AJH6Q'
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://kafka2:29092,CLIENT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:29092,CLIENT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093

    networks:
      - kafka-net
      
    volumes:
      - ./kafka2-storage:/tmp/kafka-logs

  kafka3:
    image: apache/kafka:latest
    container_name: kafka3

    ports:
      - "9095:9095"

    environment:
      CLUSTER_ID: 'Eq2RE98JRhiAGPiQ0AJH6Q'
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://kafka3:29092,CLIENT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:29092,CLIENT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - kafka-net  
    volumes:
      - ./kafka3-storage:/tmp/kafka-logs
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: pro-kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

    networks:
      - kafka-net

    environment:
      KAFKA_CLUSTERS_0_NAME: "multi-node-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"

  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "7070:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
  
    networks:
      - kafka-net

    environment:
      KAFKA_BROKERS: "kafka1:29092,kafka2:29092,kafka3:29092"

networks:
  kafka-net:
    name: kafka-net

volumes:
  kafka-logs:
    driver: local
